# Generated by Django 3.1 on 2020-08-10 07:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_auto_20200810_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 10, 10, 48, 41, 406717), editable=False),
        ),
    ]
