version: "3"   

volumes:
        postgres_data:

services:
        postgresql:
                image: postgres
                container_name: postgres
                restart: always
                environment:
                        - POSTGRES_USER=${POSTGRES_USER}
                        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
                        - POSTGRES_DB=${POSTGRES_DB}
                volumes:
                        - postgres_data:/var/lib/postgresql/data/
                ports:
                        - 5432:5432
                expose:
                        - '5432'
