# Generated by Django 3.1 on 2020-08-09 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_auto_20200809_0122"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.CharField(default="ok", max_length=25, verbose_name="Author"),
        ),
    ]
