# Generated by Django 3.1 on 2020-08-09 22:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0012_auto_20200810_0124"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2020, 8, 10, 1, 24, 28, 849053),
                editable=False,
            ),
        ),
    ]
