# Generated by Django 3.1 on 2020-08-10 07:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20200810_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 10, 10, 42, 23, 24628), editable=False),
        ),
    ]
