# Generated by Django 3.1 on 2020-08-10 07:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_auto_20200810_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 10, 10, 50, 4, 90475), editable=False),
        ),
    ]
