# Generated by Django 3.1 on 2020-08-12 17:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_auto_20200810_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 12, 20, 55, 45, 301288), editable=False),
        ),
    ]
